name: PR Build Validation

on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - "src/**"
      - "**/*.sln"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore Todos.sln

      - name: Build solution
        run: dotnet build Todos.sln --no-restore --configuration Release

#      - name: Run tests
#        run: dotnet test tests/Todos.Backend.Tests/Todos.Tests.csproj --no-build --configuration Release --verbosity normal